---
new_page_extension: md
auto_deploy: false
admin_path: "/manager"
webhook_url: 
sections:
- type: directory
  path: content/products
  label: Products
  create: all
  match: "**/*"
  templates:
  - product
- type: directory
  path: content/categories
  label: Categories
  create: all
  match: "**/*"
  templates:
  - category
- type: directory
  path: content/subcategories
  label: Subcategories
  create: all
  match: "**/*"
  templates:
  - subcategories
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - posts
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - pages
- type: directory
  path: content/uploads
  label: Uploads
  create: all
  match: "**/*"
  hidden: true
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: 0.42.1
