---
new_page_extension: md
auto_deploy: false
admin_path: "/manager"
webhook_url: 
sections: 
upload_dir: blackbillion
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: 0.38.1
