---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: content/products
  label: Products
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: content/categories
  label: Categories
  create: all
  match: "**/*"
  templates:
  - category
- type: directory
  path: content/subcategories
  label: Subcategories
  create: all
  match: "**/*"
  templates:
  - subcategories
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - posts
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - pages
  - homepage
- type: directory
  path: content/uploads
  label: Uploads
  create: all
  match: "**/*"
  hidden: true
- type: heading
  label: other
- type: document
  path: data/settings.yaml
  label: Settings
- type: document
  path: data/taxonomy_data.yaml
  label: Taxonomy Info
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: '0.49'
