---
new_page_extension: md
auto_deploy: false
admin_path: "/manager"
webhook_url: 
sections: 
  categories:
    default_front_matter_template: category
  posts:
    default_front_matter_template: post
  page:
    default_front_matter_template: page
  subcategories:
    default_front_matter_template: subcategory
upload_dir: static/images
public_path: "/images"
front_matter_path: "/images"
use_front_matter_path: false
file_template: ":filename:"
version: 0.38.1
