---
new_page_extension: md
auto_deploy: false
admin_path: "/manager"
webhook_url: 
sections:
- path: content/products
  label: Products
  create: all
  templates:
  - product
  default_front_matter_template: product
- path: content/categories
  label: Categories
  create: all
  templates:
  - category
  - product
- path: content/subcategories
  label: Subcategories
  create: all
  templates:
  - subcategory
- path: content/posts
  label: Posts
  create: all
  templates:
  - post
- path: content
  label: Pages
  create: all
  templates:
  - page.yml
- path: content/uploads
  label: Uploads
  create: all
  hidden: true
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: 0.42.1
