---
new_page_extension: md
auto_deploy: false
admin_path: "/manager"
webhook_url: 
sections:
- path: content/products
  label: Products
  create: all
  default_front_matter_template: product
- path: content/posts
  label: Posts
  create: all
  default_front_matter_template: post
- path: content
  label: Pages
  create: all
  default_front_matter_template: page
- path: content/uploads
  label: Uploads
  create: all
  hidden: true
- path: content/subcategories
  label: Subcategories
  create: all
  default_front_matter_template: subcategory
- path: content/categories
  label: Categories
  create: all
  default_front_matter_template: category
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: 0.42.1
