---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Homepage
- type: directory
  path: content
  label: Pages
  create: documents
  match: "*"
  exclude: _index.md
  templates:
  - pages
  - question-answer-page
- type: directory
  path: content/products
  label: Products
  create: documents
  match: "**/*"
  templates:
  - product
- type: directory
  path: content/categories
  label: Categories
  create: documents
  match: "**/*"
  templates:
  - category
- type: directory
  path: content/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - posts
- type: heading
  label: other
- type: document
  path: data/settings.yaml
  label: Settings
- type: document
  path: data/taxonomy_data.yaml
  label: Taxonomy Info
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.5
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -F -E --renderToDisk --port 8080 --bind
    0.0.0.0
version: '0.49'
