---
pages:
- posts/hello-world-.md
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: datetime
  name: date
  label: Date
  config:
    required: false
- type: file
  name: main_image
  label: Main Image
- type: include
  name: seo
  label: Seo
  template: seo-fields
- type: tag_list
  name: tags
  label: Tags
- type: select
  name: type
  config:
    source:
      type: simple
    required: true
    options:
    - default
  label: type
  hidden: true
  default: default
