---
hide_body: true
is_partial: false
fields:
- type: include
  name: main_fields
  label: Main Fields
  template: product-template-tops
- type: select
  name: categories
  config:
    source:
      type: datafiles
      file: product_categories-yaml
      path: 
    required: true
  label: Main Category
  hidden: true
  default: outerwear
- type: select
  name: subcategories
  config:
    source:
      type: datafiles
      file: product_categories-yaml
      path: outerwear
  label: Subcategory
- type: include
  name: seo
  label: Seo
  template: seo-fields
