---
hide_body: false
is_partial: true
fields:
- type: text
  label: Grid Name
  name: name
  config:
    required: true
- type: text
  label: Heading
  name: heading
  description: Text to appear above the grid. Leave blank to hide the heading.
- type: list
  config:
    use_select: true
    source:
      type: pages
      section: products
  label: Products
  name: products
  description: Choose the products you'd like to include in this grid.
