---
pages:
- products/sample-men-s-product.md
- products/sample-women-s-product.md
hide_body: true
is_partial: false
fields:
- type: include
  template: product-template-tops
  label: Main Fields
  name: main_fields
- type: select
  config:
    source:
      type: datafiles
      file: product_categories-yaml
    required: true
  hidden: true
  label: Main Category
  name: categories
  default: tops
- type: select
  name: subcategories
  config:
    source:
      type: datafiles
      file: product_categories-yaml
      path: tops
  label: SubCategory
  description: Choose a category. If you don't see the one you are looking for add
    it to the "Product Categories" section in the menu.
- type: include
  template: seo-fields
  label: Seo
  name: seo
