---
pages:
- products/test-product.md
- products/sample-women-s-product.md
- products/sample-men-s-product.md
hide_body: true
is_partial: false
fields:
- type: select
  config:
    source:
      type: simple
      file: product_categories-yaml
    required: true
    options:
    - tops
  hidden: false
  label: Main Category
  name: categories
  default: tops
- type: select
  name: subcategories
  config:
    source:
      type: datafiles
      file: product_categories-yaml
      path: tops
  label: SubCategory
  description: Choose a subcategory. If you don't see the subcategory you are looking
    for, go to "Product Categories" in the menu on the left and add it there.
- type: include
  template: product-template-tops
  label: Main Fields
  name: main_fields
- type: include
  template: seo-fields
  label: Seo
  name: seo
