---
pages:
- products/sample-hat.md
- products/sample-women-s-tee.md
- products/sample-men-s-tee.md
hide_body: true
is_partial: false
fields:
- type: include
  template: product-template-tops
  label: Main Fields
  name: main_fields
- type: include
  name: seo
  label: Seo
  template: seo-fields
