---
hide_body: true
is_partial: false
fields:
- type: include
  template: product-template-tops
  label: Main Fields
  name: main_fields
- type: field_group
  name: seo
  label: SEO
  fields:
  - type: include
    template: seo-fields
    label: Seo
    name: seo
  description: Search Engine Optimization
