---
pages:
- products/_index.md
- products/outerwear/_index.md
- products/accessories/_index.md
- products/hats/_index.md
- products/bottoms/_index.md
- products/tops/_index.md
hide_body: true
is_partial: false
fields:
- type: text
  name: title
  label: Admin Label
  config:
    required: true
  description: Label for website admin area
  default: List Page
  hidden: true
- name: name
  label: Navigation Title
  type: text
  hidden: false
  default: ''
  description: Text that appears in the sorting fields, breadcrumbs, and page navigation
  config:
    required: false
- type: text
  name: meta_title
  label: Meta Title
  description: Page title to appear in website and search engines
  config:
    required: true
  default: ''
- type: text
  name: meta_description
  label: Meta Description
  description: Description for search engines
- type: file
  name: main_image
  label: main Image
  description: Image for search engines and for preview to appear on social media
    sites
- name: type
  label: Type
  type: text
  hidden: true
  default: products
  config:
    required: true
